# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - cleanupAttrs
  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  # disabled by default
  - removeTitle
  # only non-meaningful by default
  - removeDesc
  - removeUselessDefs
  # disabled by default
  - removeXMLNS
  - removeEditorsNSData
  - removeEmptyAttrs
  - removeHiddenElems
  - removeEmptyText
  - removeEmptyContainers
  # disabled by default
  - removeViewBox
  - cleanupEnableBackground
  - minifyStyles
  - convertStyleToAttrs
  - convertColors
  - convertPathData
  - convertTransform
  - removeUnknownsAndDefaults
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeUnusedNS
  - cleanupIDs
  - cleanupNumericValues
  - cleanupListOfValues
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  # disabled by default
  - removeRasterImages
  - mergePaths
  - convertShapeToPath
  # disabled by default
  - sortAttrs
  # disabled by default
  - transformsWithOnePath
  # disabled by default
  - removeDimensions
  # disabled by default
  - removeAttrs
  # disabled by default
  - removeElementsByAttr
  # disabled by default
  - addClassesToSVGElement
  # disabled by default
  - addAttributesToSVGElement
  # disabled by default
  - removeStyleElement

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
# js2svg:
#  pretty: true
#  indent: '  '
